### ISSUE TITLE
Possible bug in "submitTransaction" method

### ISSUE THREAD

**Issue by ypopovych** [blockfrost/blockfrost-swift#2]
Hi

Seems as `CardanoTransactionsAPI.submitTransactionWithRequestBuilder` method misses the `config` parameter in RequestBuilder initialization because it can't be used with custom config, only with shared one

Thanks,
Yehor

**Comment by ph4r05** [comment]
thanks for the report @ypopovych! Sorry I missed it when it was submitted.
