### ISSUE TITLE
Change url in Podspec to HTTPS one.

### ISSUE THREAD

**Issue by ypopovych** [blockfrost/blockfrost-swift#5]
Hello.

Currently, in Podspec we have an SSH URL for sources. It breaks build on CI systems (sources can't be downloaded anonymously through SSH on GitHub).

Can you, please, change it to HTTPS one and upload the new version of the library?

I think `s.source` line in Podspec can be changed to:
```Ruby
s.source = { :git => 'https://github.com/blockfrost/blockfrost-swift.git', :tag => s.version.to_s }
```

Thanks.

**Comment by ph4r05** [comment]
Sure! Will release it today

**Comment by ph4r05** [comment]
@ypopovych it should be fixed already.
